name: Sync ufcllm to Hugging Face Space
on:
  push:
    branches: [main]
    paths:
      - 'ufcllm/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push ufcllm folder to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "git@github.com"
          git config --global user.name "GitHub Actions"
          git subtree split --prefix ufcllm -b hf-deploy
          git push https://nx2803:$HF_TOKEN@huggingface.co/spaces/nx2803/UFC_LLM hf-deploy:main --force